### PR TITLE
fix OMJulia intoduction

### PR DESCRIPTION
**Pull request by arun3688**

### CODE REVIEW

**Comment by adeas31** [comment]
@arun3688 can you sign the CLA?

**Comment by arun3688** [comment]
@adeas31  i signed

**Comment by sjoelund** [comment]
The email used needs to match one verified in your github account. The email in the commits is set to `arun@dev`, so you need to fix the commit.

**Comment by arun3688** [comment]
@sjoelund , I have now fixed the commit with my account arun3688

**Comment by sjoelund** [comment]
Still has the same author: `Author: Arunkumar Palanisamy <arun@dev>`
Use:
```bash
git commit --amend --reset-author
```
Verify the author is correct using `git log`

**Pull request merged**
