### PR TITLE
-TLM based co-simulation users guide

### PR DESCRIPTION
**Pull request by alash325**

### CODE REVIEW

**Comment by sjoelund** [comment]
What PNG optimizer did you run on the images?

**Comment by alash325** [comment]
I didn't use PNG optimizer. Should I use PNG optimizer?  Let me know if you have any recommendation

**Comment by sjoelund** [comment]
pngout or pngcrush

**Comment by alash325** [comment]
PNG is now optimized by tinypng instead. 
I tried pngcrush first but tinypng optmized with > 60%

**Comment by sjoelund** [comment]
You should squash your commits since the point is to not add the large PNGs to the repository (and now you add two copies).

**Comment by alash325** [comment]
Squashed done. Thanks!

**Comment by sjoelund** [comment]
There are some missing files:
```
tlmcosimulation.rst:None: WARNING: image file not readable: media/tlm-file-menu.png
tlmcosimulation.rst:None: WARNING: image file not readable: media/tlm-cosimulation-plotting.png
tlmcosimulation.rst:None: WARNING: image file not readable: media/tlm-connections-popup.png
tlmcosimulation.rst:None: WARNING: image file not readable: media/tlm-change-cosimulation-parameter-popup-menu.png
```

**Pull request merged**
