### PR TITLE
added notes for initial guess with dyn. optimization

### PR DESCRIPTION
**Pull request by vruge**

### CODE REVIEW

**Comment by sjoelund** [comment]
This has LaTeX sources, right? We should start pushing the source files instead of pdf's. We can create Makefiles that generate the documentation.

**Comment by vruge** [comment]
The LaTeX source depend from 
https://github.com/modelica-tools/listings-modelica.git.

It possible to push the listing source on the top?

**Comment by sjoelund** [comment]
Yes, we should add it some time. Or one of my versions with MetaModelica support.

**Comment by sjoelund** [comment]
By the way. When working on a pull request, I suggest using a topic branch (branch named what you want to fix). If you push something into master, the pull request is updated, and it might be something not relevant to the original request.

**Comment by sjoelund** [comment]
Fixed with 336070204f5cde988b6fa04530dfd0de42ddebce. I used "git rebase -i" to remove the add+revert pdf commits so the pdf is not added to the history.

**Comment by sjoelund** [comment]
I note that \today is used and if we regenerate the pdf during the build, it will be the day of the build and not the day the file was modified. Additionally, git does not preserve the old mtime so you can't query the mtime and print the date the file was modified either.

**Pull request closed without merging**
